<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Saxotech Nivo Gallery</title>
	<style type="text/css">
		#gallery  {
			width:500px;
		}
		ul {
			margin:0;
			padding:0;
			height:300px;
		}
		
		ul li {
			list-style-type:none;
		}
	</style>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
</head>
<body>
	<h2>Nivo Slider</h2>
	
	<pbs:macro name="multimediaSlider" myCount="10" myCategory="test" myDays="5">  
	
	<!--Start Calls the jquery library for Nivo-->
	<script type="text/javascript" src="/js/jquery.nivo.gallery.min.js"></script>
	
	<script type="text/javascript">
	  $(document).ready(function() {
	      $('#gallery').nivoGallery();
	  });
	</script>
	<!--End Calls the jquery library for Nivo-->


</body>
</html>